App\Entity\Option:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
  properties:
    name:
      - Length:
          min: 5
          max: 255
          minMessage: 'Le titre doit au moins comporter 5 caractères'
          maxMessage: 'Le titre ne peut comporter que 255 caractères maximum'
      - NotBlank: ~
