

#Login
logout:
    path: /logout

login:
    path: /login
    controller: App\Controller\SecurityLoginController::login

# Home
home:
    path: /
    controller: App\Controller\HomeIndexController::index

# Property
property.index:
    path: /biens
    controller: App\Controller\PropertyIndexController::index

property.show:
    path: /biens/{slug}-{id}
    controller: App\Controller\PropertyShowController::show
    requirements:
        slug: '[a-z0-9\-]*'

#Admin Option
admin.option.index:
    path: /admin/options
    controller: App\Controller\Admin\OptionIndexController::index
    methods: GET

option.delete:
    path: /admin/options/{id}
    controller: App\Controller\Admin\OptionDeletionController::delete
    methods: DELETE
    requirements:
        id: '[0-9]*'

option.new:
    path: /admin/options/new
    controller: App\Controller\Admin\OptionCreationController::new
    methods: GET|POST

option.edit:
    path: /admin/options/{id}/edit
    controller: App\Controller\Admin\OptionEditionController::edit
    methods: GET|POST

#Admin Property
admin.property.index:
    path: /admin
    controller: App\Controller\Admin\PropertyIndexController::index

admin.property.new:
    path: /admin/properties/create
    controller: App\Controller\Admin\PropertyCreationController::new

admin.property.edit:
    path: /admin/properties/{id}
    controller: App\Controller\Admin\PropertyEditionController::edit
    methods: GET|POST

admin.property.delete:
    path: /admin/properties/{id}
    controller: App\Controller\Admin\PropertyDeletionController::delete
    methods: DELETE
